routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});






Route::middleware(['auth'])->group(function () {

    Route::get('index', function (){
        return view('index');
    })->name('home.index');

    ///// Super admin routes /////
    Route::group(['prefix'=>'admin','middleware'=>'super_admin'], function (){

        Route::resources([
            'admin'=>\App\Http\Controllers\AdminController::class]);

    });

    ///// Admin routes /////
    Route::group(['prefix'=>'admin','middleware'=>'admin'], function (){

        Route::resource('admin', \App\Http\Controllers\AdminController::class)->only([
            'index', 'show','edit','update'
        ]);

    });

    ///// Manager routes /////
    Route::group(['prefix'=>'admin','middleware'=>'manager'], function (){

        Route::resource('admin', \App\Http\Controllers\AdminController::class)->only([
            'show','edit','index'
        ]);

        Route::resource('buyer', \App\Http\Controllers\BuyerController::class)->only([
            'index'
        ]);
    });

    Route::resource('travel', \App\Http\Controllers\TravelController::class);
    Route::resource('carousel', \App\Http\Controllers\CarouselController::class);
    Route::resource('about', \App\Http\Controllers\AboutController::class);
    Route::resource('transaction', \App\Http\Controllers\TransactionController::class);
    Route::resource('client', \App\Http\Controllers\ClientController::class);

});


//Auth::routes([
//    'register' => false, // Registration Routes...
//    'reset' => false, // Password Reset Routes...
//    'verify' => false, // Email Verification Routes...
//]);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');





Route::post('message', function (\Illuminate\Http\Request $request){

    \Illuminate\Support\Facades\Http::post('https://api.telegram.org/bot5666785517:AAEB2gQEaLig1LZwojCkaZDUKvcZ_0m42-8/sendMessage', [
//        'chat_id'=>531110501,
        'chat_id'=>507405877,
        'text'=>'Name: '.$request->name.' '.' Email: '.$request->email. ' '.
            ' Phone: '.$request->phone. ' '
            .' Message: '.$request->message. ' ',
//        'parse_mode'=>'html'
    ]);

    return redirect()->route('main');


})->name('message');



Route::get('news',function (){

    $carousel = \Illuminate\Support\Facades\DB::select('select * from carousel');
    $trips = \Illuminate\Support\Facades\DB::select('select * from trips');
    $about = \Illuminate\Support\Facades\DB::select('select * from about');


    return view('turist-uz.news',compact('carousel','trips','about'));
})->name('news');



Route::post('client-pay',function (\Illuminate\Http\Request $request){
    $request->validate([
        'user_id'=>'required',
        'summa'=>'required'
    ]);

    return redirect()->to(route('pay.umrah',['click',$request->user_id,$request->summa]));
})->name('pay.click');


Route::get('',function (){

    $carousel = \Illuminate\Support\Facades\DB::select('select * from carousel');
    $trips = \Illuminate\Support\Facades\DB::select('select * from trips limit 4');
    $about = \Illuminate\Support\Facades\DB::select('select * from about');



    return view('turist-uz.index', compact('carousel','trips','about'));
})->name('main');







//handle requests from payment system
Route::any('/handle/{paysys}',function($paysys){
    (new Goodoneuz\PayUz\PayUz)->driver($paysys)->handle();
});

//redirect to payment system or payment form
Route::any('/pay/{paysys}/{key}/{amount}',function($paysys, $key, $amount){
    $model = Goodoneuz\PayUz\Services\PaymentService::convertKeyToModel($key);
    $url = request('redirect_url','/'); // redirect url after payment completed
    $pay_uz = new Goodoneuz\PayUz\PayUz;
    $pay_uz
        ->driver($paysys)
        ->redirect($model, $amount, 860, $url);
})->name('pay.umrah');

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    use HasFactory;

    protected $table = 'clients';
    public $timestamps = false;

    protected $fillable = [
        'name',
        'phone_number',
        'address'
    ];
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Models\Client;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->search){

            $client = DB::table('clients as c')
            ->leftJoin('transactions as t','c.id','=','t.transactionable_id')
            ->select('c.*',DB::raw('SUM(t.amount) as summa'))
            ->groupBy('c.id')
            ->get();

            $search = $request->search;
        }else{

            $client = DB::table('clients as c')
                ->leftJoin('transactions as t','c.id','=','t.transactionable_id')
                ->select('c.*',DB::raw('SUM(t.amount) as summa'))
                ->groupBy('c.id')
                ->get();


            $search = '';
        }

        return view('admin.client.index', compact('client','search'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'phone_number'=>'required',
            'address'=>'required',
        ]);
        $client = new Client;
        $client->name = $request->name;
        $client->phone_number = $request->phone_number;
        $client->address = $request->address;
        $client->save();


        return redirect()->route('client.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
            $transaction = \Illuminate\Support\Facades\DB::select('select t.*, c.name from transactions t
            join clients c on t.transactionable_id = c.id where c.id='.$id);



        return view('admin.client.show', compact('transaction'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
            'phone_number'=>'required',
            'address'=>'required',
        ]);
        $client = Client::find($id);
        $client->name = $request->name;
        $client->phone_number = $request->phone_number;
        $client->address = $request->address;
        $client->update();


        return redirect()->route('client.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/client/index.blade.php
@extends('layouts.main')

@section('main-content')
    <!-- /.card -->

    <div class="card">
        <div class="card-header">
            <ul class="navbar list-unstyled m-0 p-0">
                <li>
                    <h3 class="card-title">Biz haqimizda</h3>
                </li>
                <li>
                    <button type="button" class="btn btn-success float-right" data-toggle="modal" data-target="#about_add">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus" viewBox="0 0 16 16">
                            <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                            <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
                        </svg>
                    </button>
                    <div class="modal fade" id="about_add">
                        <div class="modal-dialog">
                            <div class="modal-content bg-primary">
                                <form action="{{ route('client.store') }}" method="post" enctype="multipart/form-data">

                                    <div class="modal-header">
                                        <h4 class="modal-title">Mijoz qo'shish</h4>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">

                                        @csrf
                                        <div class="card-body">
                                            <div class="form-group">
                                                <label for="exampleInputEmail1">F.I.SH</label>
                                                <input name="name" type="text" class="form-control" value="" id="exampleInputEmail1" placeholder="Ism kiriting" required>
                                            </div>

                                            <div class="form-group">
                                                <label for="exampleInputEmail1">Telefon</label>
                                                <input name="phone_number" type="number" class="form-control" value="" id="exampleInputEmail1" placeholder="Telefon kiriting" required>
                                            </div>

                                            <div class="form-group">
                                                <label for="exampleInputEmail1">Address</label>
                                                <input name="address" type="text" class="form-control" value="" id="exampleInputEmail1" placeholder="Address kiriting" required>
                                            </div>


                                            <div class="form-check">
                                                <input type="checkbox" class="form-check-input" id="exampleCheck1" required>
                                                <label class="form-check-label" for="exampleCheck1">Tekshirish</label>
                                            </div>
                                        </div>
                                        <!-- /.card-body -->
                                    </div>
                                    <div class="modal-footer justify-content-between">
                                        <button type="button" class="btn btn-outline-light" data-dismiss="modal">Yopish</button>
                                        <button type="submit" class="btn btn-outline-light">Saqlash</button>
                                    </div>

                                </form>
                            </div>
                            <!-- /.modal-content -->
                        </div>
                        <!-- /.modal-dialog -->
                    </div>
                    <!-- /.modal -->
                </li>
            </ul>
        </div>
        <!-- /.card-header -->
        <div class="card-body pt-0 table-responsive">
            <table id="example1" class="table table-bordered table-striped ">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Ism</th>
                    <th>Telefon</th>
                    <th>Summa</th>
                    <th>Address</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($client as $item)
                    <tr>
                        <td class="p-1">{{ $item->id }}</td>
                        <td class="p-1"><a href="{{ route('client.show',$item->id) }}">{{ $item->name }}</a></td>
                        <td class="p-1">{{ $item->phone_number }}</td>
                        <td class="p-1">{{ $item->summa }}</td>
                        <td class="p-1">{{ $item->address }}</td>
                        <td class="p-1">
                            <button type="button" class="btn btn-success m-0 p-1 py-0 float-right" data-toggle="modal" data-target="#update{{ $item->id }}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus" viewBox="0 0 16 16">
                                    <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                                    <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
                                </svg>
                            </button>
                            <div class="modal fade" id="update{{$item->id}}">
                                <div class="modal-dialog">
                                    <div class="modal-content bg-primary">
                                        <form action="{{ route('client.update',$item->id) }}" method="post" enctype="multipart/form-data">
                                            @csrf
                                            @method('put')
                                            <div class="modal-header">
                                                <h4 class="modal-title">Mijoz qo'shish</h4>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">

                                                @csrf
                                                <div class="card-body">
                                                    <div class="form-group">
                                                        <label for="exampleInputEmail1">F.I.SH</label>
                                                        <input name="name" type="text" class="form-control" value="{{$item->name}}" id="exampleInputEmail1" placeholder="Ism kiriting" required>
                                                    </div>

                                                    <div class="form-group">
                                                        <label for="exampleInputEmail1">Telefon</label>
                                                        <input name="phone_number" type="number" class="form-control" value="{{$item->phone_number}}" id="exampleInputEmail1" placeholder="Telefon kiriting" required>
                                                    </div>

                                                    <div class="form-group">
                                                        <label for="exampleInputEmail1">Address</label>
                                                        <input name="address" type="text" class="form-control" value="{{$item->address}}" id="exampleInputEmail1" placeholder="Address kiriting" required>
                                                    </div>


                                                    <div class="form-check">
                                                        <input type="checkbox" class="form-check-input" id="exampleCheck1" required>
                                                        <label class="form-check-label" for="exampleCheck1">Tekshirish</label>
                                                    </div>
                                                </div>
                                                <!-- /.card-body -->
                                            </div>
                                            <div class="modal-footer justify-content-between">
                                                <button type="button" class="btn btn-outline-light" data-dismiss="modal">Yopish</button>
                                                <button type="submit" class="btn btn-outline-light">Saqlash</button>
                                            </div>

                                        </form>
                                    </div>
                                    <!-- /.modal-content -->
                                </div>
                                <!-- /.modal-dialog -->
                            </div>
                            <!-- /.modal -->
                        </td>
                    </tr>

                @endforeach

                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
@endsection

resources/views/admin/client/show.blade.php
@extends('layouts.main')

@section('main-content')
    <!-- /.card -->

    <div class="card">

        <!-- /.card-header -->
        <div class="card-body pt-0 table-responsive">
            <table id="example1" class="table table-bordered table-striped ">
                <thead>
                <tr>
                    <th>N</th>
                    <th>Payment</th>
                    <th>Vaqt</th>
                    <th>Transaction</th>
                    <th>Summa</th>
                    <th>Valyuta</th>
                    <th>Holat</th>
                    <th>Mijoz</th>
                </tr>
                </thead>
                <tbody>
                @foreach($transaction as $item)
                    <tr>
                        <td>{{ $loop->index+1 }}</td>
                        <td>{{ $item->created_at }}</td>
                        <td>{{ $item->payment_system }}</td>
                        <td>{{ $item->system_transaction_id }}</td>
                        <td>{{ $item->amount }}</td>
                        <td>{{ $item->currency_code }}</td>
                        <td>{{ $item->comment }}</td>
                        <td>{{ $item->name }}</td>
                    </tr>

                @endforeach


                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
@endsection