routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});






Route::middleware(['auth'])->group(function () {

    Route::get('index', function (){
        return view('index');
    })->name('home.index');

    ///// Super admin routes /////
    Route::group(['prefix'=>'admin','middleware'=>'super_admin'], function (){

        Route::resources([
            'admin'=>\App\Http\Controllers\AdminController::class]);

    });

    ///// Admin routes /////
    Route::group(['prefix'=>'admin','middleware'=>'admin'], function (){

        Route::resource('admin', \App\Http\Controllers\AdminController::class)->only([
            'index', 'show','edit','update'
        ]);

    });

    ///// Manager routes /////
    Route::group(['prefix'=>'admin','middleware'=>'manager'], function (){

        Route::resource('admin', \App\Http\Controllers\AdminController::class)->only([
            'show','edit','index'
        ]);

        Route::resource('buyer', \App\Http\Controllers\BuyerController::class)->only([
            'index'
        ]);
    });

    Route::resource('travel', \App\Http\Controllers\TravelController::class);
    Route::resource('carousel', \App\Http\Controllers\CarouselController::class);
    Route::resource('about', \App\Http\Controllers\AboutController::class);
    Route::resource('transaction', \App\Http\Controllers\TransactionController::class);
    Route::resource('client', \App\Http\Controllers\ClientController::class);

});


//Auth::routes([
//    'register' => false, // Registration Routes...
//    'reset' => false, // Password Reset Routes...
//    'verify' => false, // Email Verification Routes...
//]);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');





Route::post('message', function (\Illuminate\Http\Request $request){

    \Illuminate\Support\Facades\Http::post('https://api.telegram.org/bot5666785517:AAEB2gQEaLig1LZwojCkaZDUKvcZ_0m42-8/sendMessage', [
//        'chat_id'=>531110501,
        'chat_id'=>507405877,
        'text'=>'Name: '.$request->name.' '.' Email: '.$request->email. ' '.
            ' Phone: '.$request->phone. ' '
            .' Message: '.$request->message. ' ',
//        'parse_mode'=>'html'
    ]);

    return redirect()->route('main');


})->name('message');



Route::get('news',function (){

    $carousel = \Illuminate\Support\Facades\DB::select('select * from carousel');
    $trips = \Illuminate\Support\Facades\DB::select('select * from trips');
    $about = \Illuminate\Support\Facades\DB::select('select * from about');


    return view('turist-uz.news',compact('carousel','trips','about'));
})->name('news');



Route::post('client-pay',function (\Illuminate\Http\Request $request){
    $request->validate([
        'user_id'=>'required',
        'summa'=>'required'
    ]);

    return redirect()->to(route('pay.umrah',['click',$request->user_id,$request->summa]));
})->name('pay.click');


Route::get('',function (){

    $carousel = \Illuminate\Support\Facades\DB::select('select * from carousel');
    $trips = \Illuminate\Support\Facades\DB::select('select * from trips limit 4');
    $about = \Illuminate\Support\Facades\DB::select('select * from about');



    return view('turist-uz.index', compact('carousel','trips','about'));
})->name('main');







//handle requests from payment system
Route::any('/handle/{paysys}',function($paysys){
    (new Goodoneuz\PayUz\PayUz)->driver($paysys)->handle();
});

//redirect to payment system or payment form
Route::any('/pay/{paysys}/{key}/{amount}',function($paysys, $key, $amount){
    $model = Goodoneuz\PayUz\Services\PaymentService::convertKeyToModel($key);
    $url = request('redirect_url','/'); // redirect url after payment completed
    $pay_uz = new Goodoneuz\PayUz\PayUz;
    $pay_uz
        ->driver($paysys)
        ->redirect($model, $amount, 860, $url);
})->name('pay.umrah');

app/Models/Travel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Travel extends Model
{
    use HasFactory;

    protected $table = 'trips';
    public $timestamps = false;

    protected $fillable = [
        'country',
        'city',
        'price',
        'img',
        'text'
    ];
}

app/Http/Controllers/TravelController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\Travel;
use Illuminate\Support\Facades\File;


class TravelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {


        if ($request->search){
            $travels = \Illuminate\Support\Facades\DB::select('select * from trips where country like "%'.$request->search.'%"');

            $search = $request->search;
        }else{
            $travels = \Illuminate\Support\Facades\DB::select('select * from trips');

            $search = '';
        }

        return view('admin.travel.index', compact('travels','search'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'country'=>'required',
            'city'=>'required',
            'price'=>'required',
            'text'=>'required',
        ]);


        if ($request->hasFile('img')){
            $filename = time().rand(1000, 9999).".".$request->img->extension();
            $request->img->move(public_path('assets-turist/images'),$filename);
//            $request->file('img')->storeAs('public/images',$filename);

            $travel = Travel::create([
                'country'=>$request->country,
                'city'=>$request->city,
                'price'=>$request->price,
                'img'=>$filename,
                'text'=>$request->text,
            ]);

        }else{

            $travel = Travel::create([
                'country'=>$request->country,
                'city'=>$request->city,
                'price'=>$request->price,
                'img'=>'noimage',
                'text'=>$request->text,
            ]);

        }
            return redirect()->route('travel.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $travel = Travel::find($id);
        if (File::exists(public_path("app/public/images/".$travel->img))){
            File::delete(public_path("app/public/images/".$travel->img));
        }
        $travel->delete();


        return redirect()->route('travel.index');
    }
}

resources/views/admin/travel/index.blade.php
@extends('layouts.main')

@section('main-content')
    <!-- /.card -->

    <div class="card">
        <div class="card-header">
            <ul class="navbar list-unstyled m-0 p-0">
                <li>
                    <h3 class="card-title">Travel</h3>
                </li>
                <li>
                    <!-- SEARCH FORM -->
                    <form action="{{ route('travel.index') }}" method="get" class="form-inline m-0 ml-md-3">
                        @csrf
                        <div class="input-group input-group-sm">
                            <input name="search" value="{{ $search }}" class="form-control form-control-navbar" type="search" placeholder="Qidirish" aria-label="Search">
                            <div class="input-group-append">
                                <button class="btn btn-success" type="submit">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </li>
            </ul>
        </div>
        <!-- /.card-header -->
        <div class="card-body pt-0 table-responsive">
            <table id="example1" class="table table-bordered table-striped ">
                <thead>
                <tr>
                    <th>N</th>
                    <th>Davlat</th>
                    <th>Shahar</th>
                    <th>Narx</th>
                    <th>Rasm</th>
                    <th>Text</th>
                    <th>
                        @if(Auth::user()->role == 1)
                            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#travel_add">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus" viewBox="0 0 16 16">
                                    <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                                    <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
                                </svg>
                            </button>
                            <div class="modal fade" id="travel_add">
                                <div class="modal-dialog">
                                    <div class="modal-content bg-primary">
                                        <form action="{{ route('travel.store') }}" method="post" enctype="multipart/form-data">

                                            <div class="modal-header">
                                                <h4 class="modal-title">Travel qo'shish</h4>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">

                                                @csrf
                                                <div class="card-body">
                                                    <div class="form-group">
                                                        <label for="exampleInputEmail1">Davlat</label>
                                                        <input name="country" type="text" class="form-control" value="" id="exampleInputEmail1" placeholder="Davlat kiriting">
                                                    </div>

                                                    <div class="form-group">
                                                        <label for="exampleInputEmail1">Shahar</label>
                                                        <input name="city" type="text" class="form-control" value="" id="exampleInputEmail1" placeholder="Shahar kiriting">
                                                    </div>

                                                    <div class="form-group">
                                                        <label for="exampleInputEmail1">Narx</label>
                                                        <input name="price" type="text" class="form-control" value="" id="exampleInputEmail1" placeholder="Narx kiriting">
                                                    </div>

                                                    <div class="form-group">
                                                        <label for="exampleInputEmail1">Text</label>
                                                        <input name="text" type="text" class="form-control" value="" id="exampleInputEmail1" placeholder="Text kiriting">
                                                    </div>

                                                    <div class="row">
                                                        <div class="col-6">
                                                            <div class="form-group">
                                                                <label for="exampleInputFile">Rasm</label>
                                                                <div class="input-group">
                                                                    <div class="custom-file">
                                                                        <input name="img" id="imgInp" onchange="preview(travel_image)" type="file" class="custom-file-input" id="exampleInputFile">
                                                                        <label class="custom-file-label" for="exampleInputFile">Tanlang</label>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="col-6">
                                                            <label class="mb-2" for="image"><b>Rasm</b></label>
                                                            <img id="travel_image" class="ml-2" src="" width="100px" height="100px" alt="Image"/>
                                                        </div>
                                                    </div>

                                                    <div class="form-check">
                                                        <input type="checkbox" class="form-check-input" id="exampleCheck1" required>
                                                        <label class="form-check-label" for="exampleCheck1">Tekshirish</label>
                                                    </div>
                                                </div>
                                                <!-- /.card-body -->
                                            </div>
                                            <div class="modal-footer justify-content-between">
                                                <button type="button" class="btn btn-outline-light" data-dismiss="modal">Yopish</button>
                                                <button type="submit" class="btn btn-outline-light">Saqlash</button>
                                            </div>

                                        </form>
                                    </div>
                                    <!-- /.modal-content -->
                                </div>
                                <!-- /.modal-dialog -->
                            </div>
                            <!-- /.modal -->
                        @else
                            Huquq
                        @endif

                    </th>
                </tr>
                </thead>
                <tbody>
                @foreach($travels as $travel)
                    <tr>
                        <td>{{ $loop->index+1 }}</td>
                        <td>{{ $travel->country }}</td>
                        <td>{{ $travel->city }}</td>
                        <td>{{ $travel->price }}</td>
                        <td>
                            <img src="{{ asset('public/assets-turist/images/'.$travel->img) }}" width="150px">
                        </td>
                        <td>{{ $travel->text }}</td>
                        <td>

                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal-danger{{ $travel->id }}">
                                <i class="fas fa-trash m-0 p-0"></i>
                            </button>

                            <div class="modal fade" id="modal-danger{{ $travel->id }}">
                                <div class="modal-dialog">
                                    <div class="modal-content bg-danger">
                                        <div class="modal-header">
                                            <h4 class="modal-title">O'chirish</h4>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <p>O'chirishni xohlaysizmi?</p>
                                        </div>
                                        <div class="modal-footer justify-content-between">
                                            <button type="button" class="btn btn-outline-light" data-dismiss="modal">Close</button>
                                            <form class="d-inline" action="{{ route('travel.destroy',$travel->id) }}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-outline-light">
                                                    O'chirish
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                    <!-- /.modal-content -->
                                </div>
                                <!-- /.modal-dialog -->
                            </div>
                            <!-- /.modal -->
                        </td>

                    </tr>

                @endforeach


                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
@endsection